var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

var ClaimSchema = new Schema({
	requestID : String,
    itemBrand : String,
    itemID : String,
    serialNo : String,
    claimType : String,
    requesterID : String,
    requestCategory  : String,
    requestStatus : { type: String, default: 'New' },
    requestApproved : { type: Boolean, default: false },
    requestCompleted : { type: Boolean, default: false },
    requestTimestamp : { type: Date, default: Date.now },
    claimNotes : String,
    requestAmount : String,
    AccountID : String,
    ShipID : String,
    OrderNo : String,
    InvoiceNo : String,
    InvoiceDate : String,
    SalesLoc : String,
    ShipLoc : String,
    ClimPO : String,
    DealerCost : String,
    ClimCost : String,
    ClimReceiveDate : { type: Date},
    ClimInvoiceDate : { type: Date},
    AccountID : String,
    ShipID : String,
    AccountName : String,
    ShipName : String,
    Address : String,
    Phone : String,
    Fax : String,
    OrderNo : String,
    InvoiceNo : String,
    InvDate : String,
    SalesLoc : String,
    ShipLoc : String,
    ClimPO : String,
    DealerCost : String,
    ClimCost : String,
    ClimReceiveDate : { type: Date},
    ClimInvoiceDate : { type: Date}
});



module.exports = mongoose.model('ClaimModel', ClaimSchema);
